### ISSUE TITLE
-s, --style option is ignored

### ISSUE THREAD

**Issue by jednano** [sprity/sprity-cli#1]
It seems that if I specify the `-s` or `--style` option that it completely ignores my path and writes the Sass file to the same location as the sprite images. I am using the following command:

```
$ sprity create ./dist/images/sprites "images/sprites/foo/*.png" --template sprity-scss.hbs
--style dist/styles/sprites.scss
```

This writes `sprites.scss` into my `./dist/images/sprites` folder. Furthermore, if I use the `--split` option it doesn't write a Sass file at all! That's using the following command:

```
$ sprity create ./dist/images/sprites "images/sprites/**/*.png" --template sprity-scss.hbs
--style dist/styles/sprites.scss --split
```

**Comment by NickVanHolsbeeck** [comment]
How did you solve this? Got the same issue

**Comment by jednano** [comment]
No idea. This was eons ago.

**Comment by NickVanHolsbeeck** [comment]
Solved it with the gulp-if => if images write to ./images/ and else write to ./css/ e.g.
