### ISSUE TITLE
Clarify --split usage

### ISSUE THREAD

**Issue by jednano** [sprity/sprity-cli#2]
How is the source path glob supposed to be formatted to support the `--split` option? I have the following command:

```
$ sprity create ./dist/images/sprites "images/sprites/**/*.png" --template sprity-scss.hbs
--style "dist/styles/sprites.scss" --split
```

It seemed I had this working at some point as far as generating images, but it only generated images for 17 or so of the 27 folders I had inside my sprites folder. Also, I can't even seem to reproduce this result any more. Currently, I get no generated images and no warnings/errors about what went wrong.

**Comment by aslansky** [comment]
Problems with the split option should be fixed in sprity 1.0.4. I also added more documentation for this feature (https://github.com/sprity/sprity#how-to-use-split-option).
