### ISSUE TITLE
sprity install sass doesn't seem to work globally

### ISSUE THREAD

**Issue by ZeeCoder** [sprity/sprity-cli#3]
I installed sprity-cli globally, then tried to install the sass preprocessor by running `sprity install sass`.

It reported that the installation was successful, but then trying to use the `sass` preprocessor didn't work.

Running `npm install -g sprity-sass` solved the problem, so I think `sprity install <x>` doesn't work globally.

Also note that I was in a project's root folder while running these commands.

**Comment by joseSquare1** [comment]
I can confirm this problem, both sprity-sass and sprity-lwip must be installed globally if you installed sprity globally.
